### ISSUE TITLE
Architect

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-6-diagrama-de-clases-recyclanexus#1]
[Practica3-Architect-LuzArleth-Saul.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-diagrama-de-clases-recyclanexus/files/14717066/Practica3-Architect-LuzArleth-Saul.pdf)

**Comment by isairey** [comment]
Portada: 25
Procedimiento: 25
Figuras, ilustraciones y fotografías.: 17
Resultados y conclusiones: 25
Calificación: 18.4
Nota: Faltaron imágenes

**Comment by josealfredo79** [comment]
bien hecho y revisado...
